serve:
  public:
    cors:
      enabled: true
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
  admin:
    cors:
      enabled: true
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout
  consent: http://127.0.0.1:3000/consent

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
