services:
  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: kazusa
      POSTGRES_USER: vcl
      POSTGRES_PASSWORD: vcl
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  kratos-migrate:
    depends_on:
      - postgres-db
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=${DATABASE_URL}
    entrypoint: /bin/sh -c "/usr/bin/kratos -c /etc/config/kratos/${KRATOS_CONFIG_NAME} migrate sql -e --yes >/dev/null 2>&1"
    restart: on-failure
    volumes:
      - config-data:/etc/config

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.2.0
    environment:
    - COURIER_SMTP_CONNECTION_URI
    - SELFSERVICE_FLOWS_SETTINGS_AFTER_HOOKS_0_CONFIG_URL
    - SELFSERVICE_FLOWS_SETTINGS_AFTER_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
    - SECRETS_COOKIE
    - SECRETS_CIPHER
    - DSN=${DATABASE_URL}
    - LOG_LEVEL
    ports:
      - '4433:4433' # public
      # - '4434:4434' # admin. can be uncommented for testing- but should be removed in prod.
    restart: unless-stopped
    command: serve -c /etc/config/kratos/${KRATOS_CONFIG_NAME} --dev --watch-courier
    volumes:
      - config-data:/etc/config

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.2.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4435
    ports:
      - "4435:4435"
    restart: on-failure

  server:
    depends_on:
      - postgres-db
      - redis
    build: .
    # image: ghcr.io/vncommunityleague/kazusa:main
    ports:
      - "4000:4000"
    environment:
      - ORY_AUTH_BEARER
      - HOST_ADDR
      - SITE_URL
      - DATABASE_URL
      - REDIS_URL
      - KRATOS_URL
      - OSU_CLIENT_ID
      - OSU_CLIENT_SECRET
      - JWKS_URL
    volumes:
      - config-data:/etc/config

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
      - server
    ports:
      - "4455:4455"
      - "4456:4456"
    command:
      serve proxy -c "/etc/config/oathkeeper/${OATHKEEPER_CONFIG_NAME}"
    environment:
      - LOG_LEVEL=debug
    restart: unless-stopped
    volumes:
      - config-data:/etc/config

volumes:
  db-data:
  redis-data:
  config-data:
